version: '3.9'

services:
  app:
    image: thecodingmachine/php:${PHP_VERSION:-7.4}-v4-cli-node16
    depends_on:
      apache:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      PHP_EXTENSION_INTL: 1
      TYPO3_INSTALL_ADMIN_PASSWORD: password
      TYPO3_INSTALL_ADMIN_USER: admin
      TYPO3_INSTALL_DB_DBNAME: typo3
      TYPO3_INSTALL_DB_DRIVER: mysqli
      TYPO3_INSTALL_DB_HOST: mysql
      TYPO3_INSTALL_DB_PASSWORD: root
      TYPO3_INSTALL_DB_USE_EXISTING: 'true'
      TYPO3_INSTALL_DB_USER: root
      TYPO3_INSTALL_SITE_BASE_URL: http://apache/
      TYPO3_INSTALL_SITE_SETUP_TYPE: site
      TYPO3_INSTALL_WEB_SERVER_CONFIG: apache
      TYPO3_PATH_APP: /usr/src/app/Tests/_output
      TYPO3_PATH_ROOT: /usr/src/app/Tests/_output
      TYPO3_PATH_WEB: /usr/src/app/Tests/_output
      TYPO3_VERSION: ${TYPO3_VERSION:-^11.5}
    volumes:
      - ./:/usr/src/app

  apache:
    image: thecodingmachine/php:${PHP_VERSION:-7.4}-v4-apache
    environment:
      APACHE_DOCUMENT_ROOT: Tests/_output
      TYPO3_PATH_APP: /var/www/html/Tests/_output
      TYPO3_PATH_ROOT: /var/www/html/Tests/_output
      TYPO3_PATH_WEB: /var/www/html/Tests/_output
    healthcheck:
      test: ["CMD", "curl", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: typo3
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    tmpfs:
      - /var/lib/mysql
