services:
  app:
    image: thecodingmachine/php:${PHP_VERSION:-8.1}-v4-cli
    depends_on:
      apache:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      PHP_EXTENSION_INTL: 1
      SERVER_SOFTWARE: Apache
      TYPO3_DB_DRIVER: mysqli
      TYPO3_DB_HOST: mysql
      TYPO3_DB_PORT: 3306
      TYPO3_DB_USERNAME: root
      TYPO3_DB_PASSWORD: root
      TYPO3_DB_DBNAME: typo3
      TYPO3_PROJECT_NAME: Test
      TYPO3_SETUP_ADMIN_EMAIL: admin@example.org
      TYPO3_SETUP_ADMIN_USERNAME: admin
      TYPO3_SETUP_ADMIN_PASSWORD: Passw0rd!
      TYPO3_SETUP_CREATE_SITE: http://apache/
      TYPO3_SERVER_TYPE: apache
      TYPO3_INSTALL_ADMIN_PASSWORD: Passw0rd!
      TYPO3_INSTALL_ADMIN_USER: admin
      TYPO3_INSTALL_DB_DBNAME: typo3
      TYPO3_INSTALL_DB_DRIVER: mysqli
      TYPO3_INSTALL_DB_HOST: mysql
      TYPO3_INSTALL_DB_PASSWORD: root
      TYPO3_INSTALL_DB_USE_EXISTING: 'true'
      TYPO3_INSTALL_DB_USER: root
      TYPO3_INSTALL_SITE_BASE_URL: http://apache/
      TYPO3_INSTALL_SITE_SETUP_TYPE: site
      TYPO3_INSTALL_WEB_SERVER_CONFIG: apache
      TYPO3_PATH_APP: /usr/src/app/Tests/_output
      TYPO3_PATH_ROOT: /usr/src/app/Tests/_output
      TYPO3_PATH_WEB: /usr/src/app/Tests/_output
      TYPO3_VERSION: ${TYPO3_VERSION:-^12.4}
    volumes:
      - ./:/usr/src/app

  apache:
    image: thecodingmachine/php:${PHP_VERSION:-8.1}-v4-apache
    environment:
      APACHE_DOCUMENT_ROOT: Tests/_output
      TYPO3_PATH_APP: /var/www/html/Tests/_output
      TYPO3_PATH_ROOT: /var/www/html/Tests/_output
      TYPO3_PATH_WEB: /var/www/html/Tests/_output
    healthcheck:
      test: ["CMD", "curl", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: typo3
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    tmpfs:
      - /var/lib/mysql
