services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pagemachine\OpcacheControl\:
    resource: '../Classes/*'

  Pagemachine\OpcacheControl\Action\OpcacheResetAction:
    public: true

  Pagemachine\OpcacheControl\Action\OpcacheStatusAction:
    public: true

  Pagemachine\OpcacheControl\Command\OpcacheResetCommand:
    tags:
      -
        name: console.command
        command: opcache:reset
        description: Reset PHP opcache for web

  Pagemachine\OpcacheControl\Command\OpcacheStatusCommand:
    tags:
      -
        name: console.command
        command: opcache:status
        description: Output PHP opcache status for web
