name: CI

on:
  push:
    branches:
     - master
    tags:
      - '*'
  pull_request:
    branches:
     - master

jobs:
  build:
    name: 'PHP ${{ matrix.php }}, TYPO3 ${{ matrix.typo3 }}'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.2'
        typo3:
          - ^11.5
          - ^12.4

    steps:
      - uses: actions/checkout@v4

      - name: Build
        env:
          PHP_VERSION: ${{matrix.php}}
          TYPO3_VERSION: ${{matrix.typo3}}
        run: docker compose run --rm app composer build

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: typo3-var-${{matrix.php}}-${{matrix.typo3}}
          path: Tests/_output/typo3temp/var

      - name: Cleanup
        if: ${{ always() }}
        run: docker compose down --volumes
